server:
  port: 0
spring:
  application:
    name: relocation-service
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    banner-mode: "off"
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    by.javaguru.profiler: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  config: env/logback-spring-local.xml

image:
  storage-dir: ${IMAGES_STORAGE_FOLDER}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1 # приоритет выполнения аспекта @CircuitBreaker (чтобы первым был CircuitBreaker а не ретрай)
    configs:
      default:
        slidingWindowType: COUNT_BASED # Тип окна статистики. COUNT_BASED/TIME_BASED Статистика по количеству последних вызовов/ за промежуток времени
        slidingWindowSize: 10 # если COUNT_BASED сколько запросов анализируется, или TIME_BASED за сколько секунд анализируется
        minimumNumberOfCalls: 5 # Минимальное количество вызовов до начала анализа. После пятого начинается вычисление процента ошибок
        failureRateThreshold: 50 # Процент ошибок, после которого цепь открывается
        waitDurationInOpenState: 10s # Сколько времени цепь остается открытой. для запросов CallNotPermittedException
        permittedNumberOfCallsInHalfOpenState: 3 # Сколько пробных запросов разрешено
        ignoreExceptions:
          - by.javaguru.jdmik7.relocation.api.exception.ServiceBadRequestException
    instances:
      accountingCircuitBreaker:
        baseConfig: default
      profilerCircuitBreaker:
        baseConfig: default
      securityCircuitBreaker:
        baseConfig: default
  retry:
    retry-aspect-order: 2 # порядок выполнения Spring AOP аспектов (тоесть вторым)
    configs:
      default:
        max-attempts: 3 # сколько всего попыток
        wait-duration: 10s # пауза между попытками
        ignoreExceptions:
          - by.javaguru.jdmik7.relocation.api.exception.ServiceBadRequestException
    instances:
      accountingRetry:
        baseConfig: default
      profilerRetry:
        baseConfig: default
      securityRetry:
        baseConfig: default
  
